name: 'Test Puzzle Template'
slug: 'test_template'
description: 'A test puzzle description'
type: 'logic'
author: 'sam.baynham@gmail.com'
credits:
    - 'Sam Baynham'
    - 'Betsy Ogilvy'
configOptions:
    

