/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/puzzles/static/casebook/{instanceCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a CasebookDto resource.
         * @description Retrieves a CasebookDto resource.
         */
        get: operations["api_puzzlesstaticcasebook_instanceCode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/puzzles/static/casebook/{instanceCode}/subjects/{subjectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a CasebookSubjectDto resource.
         * @description Retrieves a CasebookSubjectDto resource.
         */
        get: operations["api_puzzlesstaticcasebook_instanceCodesubjects_subjectId_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dice/{rollState}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of DiceRoll resources.
         * @description Retrieves the collection of DiceRoll resources.
         */
        get: operations["api_dice_rollState_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a QuoteDto resource.
         * @description Retrieves a QuoteDto resource.
         */
        get: operations["api_quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "CasebookDto.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            instanceCode?: string;
            name?: string;
            brief?: string;
        };
        "CasebookSubjectDto.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            id?: number;
            name?: string;
            description?: string;
            type?: string;
            imageUri?: string | null;
            revealedClues?: null[];
        };
        "DiceRoll.jsonld": {
            id?: string;
            dieSides?: number;
            roll?: number;
            total?: number;
            bonus?: number | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string;
            /**
             * @default 400
             * @example 404
             */
            status: number;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string;
            /**
             * @default 400
             * @example 404
             */
            status: number;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: {
            member: unknown[];
            totalItems?: number;
            /**
             * @example {
             *       "@id": "string",
             *       "type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        "QuoteDto.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            quote?: string;
            citation?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_puzzlesstaticcasebook_instanceCode_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CasebookDto identifier */
                instanceCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CasebookDto resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["CasebookDto.jsonld"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_puzzlesstaticcasebook_instanceCodesubjects_subjectId_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description CasebookSubjectDto identifier */
                instanceCode: string;
                /** @description CasebookSubjectDto identifier */
                subjectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CasebookSubjectDto resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["CasebookSubjectDto.jsonld"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_dice_rollState_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path: {
                /** @description DiceRoll identifier */
                rollState: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DiceRoll collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member?: components["schemas"]["DiceRoll.jsonld"][];
                    };
                };
            };
        };
    };
    api_quote_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QuoteDto resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["QuoteDto.jsonld"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
